version: '3.4'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
    ports:
      - "5430:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
