version: '3.4'

services:
  postgres:
    container_name: kfn-api-postgres
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
    ports:
      - "5430:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  redis:
    container_name: kfn-api-redis
    image: redis:latest
    ports:
      - "6379:6379"
